[project]
name = "llm-cost-optimizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.118.0",
    "fastapi[standard]>=0.140.11",
    "openai>=2.47.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "torch>=2.13.0",
    "transformers>=5.14.1",
]
